name: Run Action

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  surrealdb-setup:
    runs-on: ubuntu-latest

    services:
      surrealdb:
        image: surrealdb/surrealdb:latest
        ports:
          - 8000:8000
        options: --user root --pass root

    name: Run Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Action
        uses: ./

      - name: Try to retrieve response from port 8000
        run: bash -c 'echo -n "Waiting port 8000 .."; for _ in `seq 1 40`; do echo -n .; sleep 0.5; nc -z 127.0.0.1 8000 && echo " Open." && exit ; done; echo " Timeout!" >&2; exit 1'