name: Run Action

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  surrealdb-setup:
    runs-on: ubuntu-latest

    name: Run Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Action
        uses: ./
        with:
          surrealdb_version: "1.5.4"
          surrealdb_port: "8000"
          surrealdb_username: "root"
          surrealdb_password: "root"
          surrealdb_auth: "true"
          surrealdb_strict: "true"
      
      - name: Try to retrieve response from port 8000
        run: ping -c 5 surrealdb