name: Publish

on:
  workflow_dispatch:
    inputs:
      TAG_VERSION:
        description: 'Version of the tag'
        required: true

env:
  TAG_VERSION: ${{ github.event.inputs.TAG_VERSION }}
permissions: 
  contents: write

jobs:

  ci:
    name: CI Job
    uses: ./.github/workflows/ci.yml

  update_tag:
    name: Update Tag Job
    runs-on: ubuntu-latest
    needs: [ci]
    permissions: 
      contents: write
    steps:
      - name: Add the ${{ env.TAG_VERSION }} tag to the repository
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.TAG_VERSION }}
          tag_exists_error: true
      - name: Update the ${{ env.TAG_NAME }} tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ env.TAG_VERSION }}