name: Publish

on:
  workflow_dispatch:
    inputs:
      RELEASE_NAME:
        description: 'Name of the release'
        required: true
      TAG_VERSION:
        description: 'Version of the tag'
        required: true

env:
  TAG_VERSION: ${{ github.event.inputs.TAG_VERSION }}
permissions: 
  contents: write

jobs:

  ci:
    name: CI Job
    uses: ./.github/workflows/ci.yml

  update_tag:
    name: Update Tag Job
    runs-on: ubuntu-latest
    needs: [ci]
    permissions: 
      contents: write
    steps:
      - name: Update the ${{ env.TAG_VERSION }} tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ env.TAG_VERSION }}
      - name: Create a release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_VERSION }}
          release_name: Release ${{ env.TAG_VERSION }}