name: Publish Action

on: 
  push:
    branches: [main]

jobs:
  ci:
    name: CI Job
    uses: ./.github/workflows/ci.yml
  publish:
    name: Publish To Marketplace
    uses: github-actions-publish/publish-action@v1
    with:
      tag: v1